### ISSUE TITLE
Crash in Gradient.cs

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#109]
One-time occurance, Win 11, crash happened while rendering w/o interaction

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at T3.Core.DataTypes.Gradient.Write(JsonTextWriter writer) in C:\dev\repos\t3\Core\DataTypes\Gradient.cs:line 23
   at T3.Core.Model.<>c.<.ctor>b__3_34(JsonTextWriter writer, Object obj) in C:\dev\repos\t3\Core\Resource\Model.cs:line 255
   at T3.Core.Operator.InputValue`1.ToJson(JsonTextWriter writer) in C:\dev\repos\t3\Core\Operator\Slots\InputValue.cs:line 76
   at T3.Core.SymbolJson.WriteSymbolChildren(List`1 children) in C:\dev\repos\t3\Core\Resource\SymbolJson.cs:line 120
   at T3.Core.SymbolJson.WriteSymbol(Symbol symbol) in C:\dev\repos\t3\Core\Resource\SymbolJson.cs:line 49
   at T3.Core.Model.SaveSymbolDefinitionAndSourceFiles(IEnumerable`1 valueCollection) in C:\dev\repos\t3\Core\Resource\Model.cs:line 541
   at T3.Gui.UiModel.SaveModifiedSymbols() in C:\dev\repos\t3\t3\Gui\UiModel.cs:line 311
   at T3.Gui.T3Ui.SaveModified() in C:\dev\repos\t3\t3\Gui\T3UI.cs:line 271
   at T3.Gui.AutoBackup.AutoBackup.CreateBackupCallback() in C:\dev\repos\t3\t3\Gui\AutoBackup\AutoBackup.cs:line 49
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

```

**Comment by hollyhook** [comment]
Crash just occured again.
As a consequence of the crash my operator t3 file got corrupt.
The only gradient in my project should be the one in BubbleZoom. There are two.
![image](https://user-images.githubusercontent.com/9899825/190895089-5f1b4f34-97fb-4a07-ab15-433052cc77f7.png)

**Comment by domportera** [comment]
the simple fix for this on Tooll's end would be locking that collection when it's being written. This would be blocking and *could* result in the slightest moment of stutter. it's a dumb solution, but maybe I'll make a pull request and see if it's accepted

**Comment by domportera** [comment]
Submitted a pull request on the dev branch. thanks for reporting!
https://github.com/still-scene/t3/pull/119

**Comment by hollyhook** [comment]
Thanks for caring :)

**Comment by pixtur** [comment]
Should be fixed with Pull request by @domportera
