### ISSUE TITLE
Crash caused by "dropped symbol ..." log

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#149]
Open the menu Add -> lib -> data
Drag "Example" on the dashboard -> crash

One time crash, couldn't reproduce

```
System.Text.EncoderFallbackException
  HResult=0x80070057
  Message=Unable to translate Unicode character \\uDE1E at index 103 to specified code page.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteFormatHelper(String format, ParamsArray args, Boolean appendNewLine)
   at System.IO.StreamWriter.Write(String format, Object arg0, Object arg1, Object arg2)
   at Core.Logging.FileWriter.ProcessEntry(LogEntry entry) in C:\dev\repos\t3\Core\Logging\FileWriter.cs:line 33
   at T3.Core.Logging.Log.<>c__DisplayClass17_0.<DoLog>b__0(ILogWriter writer) in C:\dev\repos\t3\Core\Logging\Log.cs:line 125
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at T3.Core.Logging.Log.DoLog(LogEntry entry) in C:\dev\repos\t3\Core\Logging\Log.cs:line 125
   at T3.Core.Logging.Log.Debug(String message) in C:\dev\repos\t3\Core\Logging\Log.cs:line 28
   at T3.Gui.Graph.GraphCanvas.DrawDropHandler() in C:\dev\repos\t3\t3\Gui\Graph\GraphCanvas.cs:line 485
   at T3.Gui.Graph.GraphCanvas.Draw(ImDrawListPtr dl, Boolean showGrid) in C:\dev\repos\t3\t3\Gui\Graph\GraphCanvas.cs:line 204
   at T3.Gui.Graph.GraphWindow.DrawContent() in C:\dev\repos\t3\t3\Gui\Graph\GraphWindow.cs:line 233
   at T3.Gui.Windows.Window.DrawOneInstance() in C:\dev\repos\t3\t3\Gui\Windows\Window.cs:line 93
   at T3.Gui.Graph.GraphWindow.DrawAllInstances() in C:\dev\repos\t3\t3\Gui\Graph\GraphWindow.cs:line 127
   at T3.Gui.Windows.Window.Draw() in C:\dev\repos\t3\t3\Gui\Windows\Window.cs:line 49
   at T3.Gui.Windows.WindowManager.Draw() in C:\dev\repos\t3\t3\Gui\Windows\WindowManager.cs:line 96
   at T3.Gui.T3Ui.Draw() in C:\dev\repos\t3\t3\Gui\T3UI.cs:line 70
   at T3.Program.<>c__DisplayClass13_0.<Main>g__RenderCallback|1() in C:\dev\repos\t3\t3\Program.cs:line 225
   at SharpDX.Windows.RenderLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at T3.Program.Main() in C:\dev\repos\t3\t3\Program.cs:line 241

```

**Comment by pixtur** [comment]
Interesting. I think I fixed this bug with https://github.com/still-scene/t3/commit/bcc4f2b5e5125e088622de501e26bce653ba4a69

**Comment by pixtur** [comment]
Can you still reproduce the issue?

**Comment by hollyhook** [comment]
Can't reproduce with v3.4

**Comment by pixtur** [comment]
YEAH!!!!
