### ISSUE TITLE
Crash in RenderVideoWindows.cs

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#155]
1) set a image as graph background
2) select Windows -> Render Video
  ->

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SharpDX.Direct3D11
  StackTrace:
   at SharpDX.Direct3D11.Texture2D.get_Description()
   at T3.Gui.Windows.RenderVideoWindow.DrawContent() in C:\dev\repos\t3\t3\Gui\Windows\RenderVideoWindow.cs:line 44
   at T3.Gui.Windows.Window.DrawOneInstance() in C:\dev\repos\t3\t3\Gui\Windows\Window.cs:line 93
   at T3.Gui.Windows.Window.Draw() in C:\dev\repos\t3\t3\Gui\Windows\Window.cs:line 53
   at T3.Gui.Windows.WindowManager.Draw() in C:\dev\repos\t3\t3\Gui\Windows\WindowManager.cs:line 96
   at T3.Gui.T3Ui.Draw() in C:\dev\repos\t3\t3\Gui\T3UI.cs:line 70
   at T3.Program.<>c__DisplayClass13_0.<Main>g__RenderCallback|1() in C:\dev\repos\t3\t3\Program.cs:line 225
   at SharpDX.Windows.RenderLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at T3.Program.Main() in C:\dev\repos\t3\t3\Program.cs:line 241

```
version 0fdd87e

**Comment by domportera** [comment]
this looks like it was fixed, is this safe to close?

**Comment by hollyhook** [comment]
it is indeed.
