### ISSUE TITLE
Crash in OperatorResources.cs

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#159]
One-time crash

I moved an operator in the Symbol Library to another folder, and then saved.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at T3.Core.OperatorResource.UpdateChangedOperatorTypes() in C:\dev\repos\t3\Core\Resource\OperatorResource.cs:line 42
   at T3.Gui.Graph.Interaction.NodeOperations.UpdateChangedOperators() in C:\dev\repos\t3\t3\Gui\Graph\Interaction\NodeOperations.cs:line 1074
   at T3.Program.<>c__DisplayClass13_0.<Main>g__RenderCallback|1() in C:\dev\repos\t3\t3\Program.cs:line 178
   at SharpDX.Windows.RenderLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at T3.Program.Main() in C:\dev\repos\t3\t3\Program.cs:line 241

```

revision b125079

**Comment by hollyhook** [comment]
Consequence of the crash were corrupt operator sub-folders

**Comment by pixtur** [comment]
I looks like something deep in the SharpDX render implementation.
Probably corrupt or modified resources.

Crashes corrupting the operator database are really bad though. We should investigate and try to reproduce them really.
