### ISSUE TITLE
Crash in PickColor.cs

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#177]
1) connect at least one Vector4 to PickColor
2) enter something which is  not a number in the index Parameter
-> crash

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection. Arg_ParamName_Name
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at T3.Operators.Types.Id_3539c3a0_73f1_412c_aad2_517810126ac6.PickColor.Update(EvaluationContext context) in C:\dev\repos\t3\Operators\Types\lib\math\vec4\PickColor.cs:line 30
   at T3.Core.Operator.Slots.Slot`1.Update(EvaluationContext context) in C:\dev\repos\t3\Core\Operator\Slots\Slot.cs:line 73
   at T3.Gui.OutputUi.OutputUi`1.Recompute(ISlot slot, EvaluationContext context) in C:\dev\repos\t3\t3\Gui\OutputUi\OutputUi.cs:line 45
   at T3.Gui.OutputUi.OutputUi`1.DrawValue(ISlot slot, EvaluationContext context, Boolean recompute) in C:\dev\repos\t3\t3\Gui\OutputUi\OutputUi.cs:line 31
   at T3.Gui.Windows.Output.OutputWindow.DrawOutput(Instance instanceForOutput, Instance instanceForEvaluation) in C:\dev\repos\t3\t3\Gui\Windows\Output\OutputWindow.cs:line 237
   at T3.Gui.Windows.Output.OutputWindow.DrawContent() in C:\dev\repos\t3\t3\Gui\Windows\Output\OutputWindow.cs:line 101
   at T3.Gui.Windows.Window.DrawOneInstance() in C:\dev\repos\t3\t3\Gui\Windows\Window.cs:line 93
   at T3.Gui.Windows.Output.OutputWindow.DrawAllInstances() in C:\dev\repos\t3\t3\Gui\Windows\Output\OutputWindow.cs:line 68
   at T3.Gui.Windows.Window.Draw() in C:\dev\repos\t3\t3\Gui\Windows\Window.cs:line 49
   at T3.Gui.Windows.WindowManager.Draw() in C:\dev\repos\t3\t3\Gui\Windows\WindowManager.cs:line 96
   at T3.Gui.T3Ui.Draw() in C:\dev\repos\t3\t3\Gui\T3UI.cs:line 70
   at T3.Program.<>c__DisplayClass13_0.<Main>g__RenderCallback|1() in C:\dev\repos\t3\t3\Program.cs:line 225
   at SharpDX.Windows.RenderLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at T3.Program.Main() in C:\dev\repos\t3\t3\Program.cs:line 241

```

**Anaysis**

This is an interesting one, because from the look of the code, the negative values are prevented. However, input of a invalid number causes the value to be -2147483648, and the negation of -2147483648 cannot be represented in an 4 byte int (MAX_INT is 2147483647). See evaluation window in screen shot

![image](https://user-images.githubusercontent.com/9899825/193452535-d55a00dc-1136-4e08-a8b9-3515d972df86.png)

Potentially this is an issue in other operators as well. Related to #123

**Comment by domportera** [comment]
wow interesting find! super edge case here, maybe we can handle this in a simple way at a low level

**Comment by hollyhook** [comment]
Fixed by #172, thanks @domportera

**Comment by pixtur** [comment]
Wow... This is just crazy! 
What a great example of open source. A perfect bug report and a valid fix a shortly thereafter. Thanks ♥

**Comment by domportera** [comment]
no problem ♥ a bit of a lucky break on the timing but for real nobody beats @hollyhook's bug reports
