### ISSUE TITLE
Unable to run after installing the .net libraroes

### ISSUE THREAD

**Issue by NicTanghe** [still-scene/t3#186]
Unable to run even after install the .net desktop libraries when using the standalone exe.

```powershell
Warning: userSettings.json doesn't exist yet
Warning: projectSettings.json doesn't exist yet
Unhandled exception. SharpDX.SharpDXException: HRESULT: [0x887A002D], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_SDK_COMPONENT_MISSING/SdkComponentMissing], Message: The application requested an operation that depends on an SDK component that is missing or mismatched.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
   at SharpDX.Direct3D11.Device..ctor(DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
   at SharpDX.Direct3D11.Device.CreateWithSwapChain(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels, SwapChainDescription swapChainDescription, Device& device, SwapChain& swapChain)
   at T3.Program.Main() in C:\Users\pixtur\dev\tooll\t3\t3\Program.cs:line 77
```

**Comment by pixtur** [comment]
In windows 10 must be active "Graphics Tools" feature.
https://msdn.microsoft.com/en-us/library/windows/apps/mt210797.aspx

Also see https://github.com/still-scene/t3/blob/master/README.md#dependencies

I hope this will fix your issue. If not, feel free to reopen it with more information.
