### ISSUE TITLE
Play video operator crash T3

### ISSUE THREAD

**Issue by microvswind** [still-scene/t3#252]
**Describe the bug**
Place play video operator on homecanvas and  T3 3.51 standalone crashed.
same result on any dev version i have tried or built.. same result in Standalone or IDE

**Please complete the following information):**
 - OS: win 10
 - Version:21H2
 - Graphics card and resolution itel(R) HD Graphics 5000
 - Microsoft surface pro 3

**To Reproduce**
1. launch T3
2. place playvideo in home canvas.
3. T3 crash without any tips.

**Expected behavior**
loading The operator PlayVideo ... should allow me to use the operator instead tooll3 is crashing upon load of this operator

**Screenshots**

https://user-images.githubusercontent.com/103630540/233410949-5c7696a8-5af1-4d21-b9a1-a63a34f30f92.mp4

![22](https://user-images.githubusercontent.com/103630540/233420114-edf17278-1655-41ca-8eb8-a23071276e86.gif)

**Additional context**
SharpDX.SharpDXException
  HResult=0x80070057
  Message=HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: 参数错误。

  Source=Operators
  StackTrace:
   at T3.Operators.Types.Id_914fb032_d7eb_414b_9e09_2bdd7049e049.PlayVideo.SetupTexture(Size2 size) in C:\Users\micro_000\T3_New\Operators\Types\lib\img\video\PlayVideo.cs:line 202
   at T3.Operators.Types.Id_914fb032_d7eb_414b_9e09_2bdd7049e049.PlayVideo.Update(EvaluationContext context) in C:\Users\micro_000\T3_New\Operators\Types\lib\img\video\PlayVideo.cs:line 79
   at T3.Core.Operator.Slots.Slot1.Update(EvaluationContext context)
   at T3.Editor.Gui.OutputUi.OutputUi1.DrawValue(ISlot slot, EvaluationContext context, Boolean recompute)
   at T3.Editor.Gui.Windows.Output.OutputWindow.UpdateAndDrawOutput(Instance instanceForOutput, Instance instanceForEvaluation)
   at T3.Editor.Gui.Windows.Output.OutputWindow.DrawContent()
   at T3.Editor.Gui.Windows.Window.DrawOneInstance()
   at T3.Editor.Gui.Windows.Output.OutputWindow.DrawAllInstances()
   at T3.Editor.Gui.Windows.Layouts.WindowManager.Draw()
   at T3.Editor.Gui.T3Ui.ProcessFrame()
   at T3.Editor.Program.<>cDisplayClass11_0.<Main>gRenderCallback|1()
   at SharpDX.Windows.RenderLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at T3.Editor.Program.Main(String[] **args)**

**Comment by microvswind** [comment]
play video and play video clip have the same issue. either place the operator from  Tab/Add Lib / symbol library

**Comment by sense-amr** [comment]
I can only imagine that this is somehow a specific problem with Microsoft Surface video handling .. as i have no issues with this operator .. loading and it plays perfectly .. even on Stanalone 3.5.1 downloaded from the Github .. 

I would think this needs to be looked into further specifically to try and identify what makes it crash with this system specifically..

**Comment by pixtur** [comment]
I can't really reproduce the issue.

So ideas what my cause this issue:
- GraphicCard or driver are no capable enough. Could you open [Demo_There] and see if it runs?
- 参数错误  (Parameter error)  triggered when creating a DirectX Texture2d indicates some kind of driver problem.

I really curious if this problem is really related to video at all or just a symptom....

**Comment by HolgerFoerterer** [comment]
@pixtur Might that be shader or shader version related?

**Comment by pixtur** [comment]
@microvswind would it be possible to get a copy of the a video that is causing the exception on your end?

**Comment by HolgerFoerterer** [comment]
Looks like it's not related to a specific video. Placing the operator alone already seems to crash the software. It may be the specific texture capabilities we request that the Surface Pro 3 doesn't support.

**Comment by pixtur** [comment]
That's sad. Maybe can prevent the crash by first checking the supported texture formats.
Also we could add a try/catch around that PlayVideo.cs call.
