### ISSUE TITLE
Operator ApplyTransformMatrix Crashes on load

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#44]
This operator Crashes Tooll3 Standalone and IDE  immediately on selection from Tab and also from ADD ->Helper Menu
![atmcrash](https://user-images.githubusercontent.com/1504019/176840258-cd5eefd3-db56-4cb9-a8f2-d8dc70c30df9.jpg)

Error log from IDE ..

System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=Operators
  StackTrace:
   at T3.Operators.Types.Id_3dae14a8_3d0b_432f_b951_bdd7afd7e5f8.ApplyTransformMatrix.Update(EvaluationContext context)
   at T3.Core.Operator.Slots.Slot`1.Update(EvaluationContext context)
   at T3.Gui.OutputUi.CommandOutputUi.Recompute(ISlot slot, EvaluationContext context)
   at T3.Gui.OutputUi.OutputUi`1.DrawValue(ISlot slot, EvaluationContext context, Boolean recompute)
   at T3.Gui.Windows.Output.OutputWindow.DrawOutput(Instance instanceForOutput, Instance instanceForEvaluation)
   at T3.Gui.Windows.Output.OutputWindow.DrawContent()
   at T3.Gui.Windows.Window.DrawOneInstance()
   at T3.Gui.Windows.Output.OutputWindow.DrawAllInstances()
   at T3.Gui.Windows.WindowManager.Draw()
   at T3.Gui.T3Ui.Draw()
   at T3.Program.<>c__DisplayClass9_0.<Main>g__RenderCallback|1()
   at SharpDX.Windows.RenderLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at T3.Program.Main()

**Comment by pixtur** [comment]
Thanks for reporting. I will look into it.

**Comment by pixtur** [comment]
Thanks for reporting. We fixed this issue in v3.3
