### ISSUE TITLE
Crash while Duplicating Keyframe in [SampleCurve] editor

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#64]
* Create [SampleCurve] Operator
* Select it and go into Parameters window
* right click near the curve
* in context menu, select Duplicate Keyframes

-> crash,  because `Current` is null

It doesn't matter if a point on the curve is selected or not, crash always occurs

t3 version taken from dev (05b728af86ab4fe43f3984d1a4c6109df396bf5b) which includes already the fix 2e9c116 - Fix curve editing in parameter view

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=t3
  StackTrace:
   at T3.Gui.Interaction.WithCurves.CurveEditing.<DrawContextMenu>b__6_0() in C:\dev\repos\t3\t3\Gui\Interaction\WithCurves\CurveEditing.cs:line 131
   at T3.Gui.CustomComponents.DrawContextMenuForScrollCanvas(Action drawMenuContent, Boolean& contextMenuIsOpen) in C:\dev\repos\t3\t3\Gui\Styling\CustomComponents.cs:line 211
   at T3.Gui.Interaction.WithCurves.CurveEditing.DrawContextMenu() in C:\dev\repos\t3\t3\Gui\Interaction\WithCurves\CurveEditing.cs:line 51
   at t3.Gui.InputUi.CombinedInputs.CurveInputEditing.CurveInteraction.SingleCurveEditCanvas.<>c__DisplayClass1_0.<Draw>g__DrawCanvasContent|0() in C:\dev\repos\t3\t3\Gui\InputUi\CombinedInputs\CurveInputEditing.cs:line 292
   at T3.Gui.Interaction.WithCurves.CurveEditCanvas.DrawCurveCanvas(Action drawAdditionalCanvasContent, Single height, EditingFlags flags) in C:\dev\repos\t3\t3\Gui\Interaction\WithCurves\CurveEditCanvas.cs:line 39
   at t3.Gui.InputUi.CombinedInputs.CurveInputEditing.CurveInteraction.SingleCurveEditCanvas.Draw(Curve curve, CurveInteraction interaction) in C:\dev\repos\t3\t3\Gui\InputUi\CombinedInputs\CurveInputEditing.cs:line 265
   at t3.Gui.InputUi.CombinedInputs.CurveInputEditing.CurveInteraction.Draw() in C:\dev\repos\t3\t3\Gui\InputUi\CombinedInputs\CurveInputEditing.cs:line 78
   at t3.Gui.InputUi.CombinedInputs.CurveInputEditing.DrawCanvasForCurve(Curve curve, EditingFlags flags) in C:\dev\repos\t3\t3\Gui\InputUi\CombinedInputs\CurveInputEditing.cs:line 49
   at T3.Gui.InputUi.CurveInputUi.DrawEditControl(String name, Curve& curve) in C:\dev\repos\t3\t3\Gui\InputUi\CombinedInputs\CurveInputUi.cs:line 40
   at T3.Gui.InputUi.InputValueUi' 1.DrawInputEdit(IInputSlot inputSlot, SymbolUi compositionUi, SymbolChildUi symbolChildUi) in C:\dev\repos\t3\t3\Gui\InputUi\InputValueUi.cs:line 404
   at T3.Gui.Windows.ParameterWindow.DrawParameters(Instance instance, SymbolUi symbolUi, SymbolChildUi symbolChildUi, SymbolUi compositionSymbolUi) in C:\dev\repos\t3\t3\Gui\Windows\ParameterWindow.cs:line 162
   at T3.Gui.Windows.ParameterWindow.DrawContent() in C:\dev\repos\t3\t3\Gui\Windows\ParameterWindow.cs:line 90
   at T3.Gui.Windows.Window.DrawOneInstance() in C:\dev\repos\t3\t3\Gui\Windows\Window.cs:line 93
   at T3.Gui.Windows.ParameterWindow.DrawAllInstances() in C:\dev\repos\t3\t3\Gui\Windows\ParameterWindow.cs:line 44
   at T3.Gui.Windows.Window.Draw() in C:\dev\repos\t3\t3\Gui\Windows\Window.cs:line 49
   at T3.Gui.Windows.WindowManager.Draw() in C:\dev\repos\t3\t3\Gui\Windows\WindowManager.cs:line 95
   at T3.Gui.T3Ui.Draw() in C:\dev\repos\t3\t3\Gui\T3UI.cs:line 91
   at T3.Program.<>c__DisplayClass10_0.<Main>g__RenderCallback|1() in C:\dev\repos\t3\t3\Program.cs:line 194
   at SharpDX.Windows.RenderLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at T3.Program.Main() in C:\dev\repos\t3\t3\Program.cs:line 210
```

**Comment by pixtur** [comment]
Thanks for reporting! Fixed in 3.3
